#! /usr/bin/env python
import copy
import logging
import os
from argparse import ArgumentParser, Namespace
from multiprocessing import Pool
from pathlib import Path
from subprocess import DEVNULL, run
from typing import Iterator
from xml.etree import ElementTree


def main() -> None:
    """
    Renders a pdf slideshow from a single svg.
    This process happens in three steps:
        0. Parse user input
        1. Split the svg into one svg file per slide
        2. Use inkscape to render each of these svgs to pdfs
        3. Combine each pdf into one master pdf
    """
    presentation = Tree()

    args = parse_args()

    level = logging.INFO if args.verbose else logging.WARNING
    logging.basicConfig(level=level, format="%(levelname)s\t%(message)s")

    for file in find_svgs(args.files):
        logging.info(f"loading {file}")
        sub_presentation = load_presentation(file)
        presentation.children.append(sub_presentation)

    merge_cmd = [
        "gs",
        "-dBATCH",
        "-dNOPAUSE",
        "-q",
        "-sDEVICE=pdfwrite",
        "-sOutputFile=" + args.output,
    ]

    pool = Pool(args.threads)

    # Split the slides, start the rendering pool
    print("\r  Splitting Slides", end="")

    os.makedirs(args.cache, exist_ok=True)
    directory = Path(args.cache)

    for count, _ in enumerate(presentation):
        svg = directory / (str(count) + ".svg")
        pdf = directory / (str(count) + ".pdf")
        merge_cmd.append(pdf)
        change = presentation.write(svg)

        if change:
            pool.apply_async(run, (["inkscape", "-o", pdf, svg],), dict(stderr=DEVNULL))

    print("\r✓ Splitting Slides")

    print("  Rendering Slides", end="")
    pool.close()
    pool.join()
    print("\r✓ Rendering Slides")

    # Merge each of the pdfs into one pdf
    print("  Merging slides", end="")
    run(merge_cmd)
    print("\r✓ Merging slides")


def parse_args() -> Namespace:

    parser = ArgumentParser(
        prog="mk_pdf",
        description="A python script to create slides using inkscape",
    )

    parser.add_argument("files", metavar="file", nargs="+", help="Inkscape file to use")

    parser.add_argument(
        "-o",
        "--output",
        metavar="file",
        help="Output for the slideshow",
        nargs="?",
        default="talk.pdf",
    )

    parser.add_argument(
        "-j",
        "--threads",
        metavar="num",
        help="How many inkscape processess to spawn",
        nargs="?",
        type=int,
        default=None,
    )

    parser.add_argument(
        "--cache",
        help="Where to cache files",
        nargs="?",
        type=str,
        metavar="dir",
        default="talk_cache",
    )

    parser.add_argument(
        "-v", "--verbose", help="Print debug information", action="store_true"
    )

    return parser.parse_args()


def inkscape(name: str) -> str:
    """Add the inkscape namespace to a name"""
    return "{http://www.inkscape.org/namespaces/inkscape}" + name


class Tree:
    def __init__(self, element: ElementTree.Element | None = None) -> None:
        self.children: list[Tree] = []
        self.element: ElementTree.Element | None = element
        self.tree: ElementTree.ElementTree | None = None
        self._visible: bool = False

    def write(self, path: Path) -> bool:
        for child in self.children:
            if child.visible and child.tree:
                tree = copy.deepcopy(child.tree)
                root = tree.getroot()

                for parent in root.findall(".//*[@style='display:none'].."):
                    for node in parent.findall(".*[@style='display:none']"):
                        parent.remove(node)

                if path.exists():
                    old = ElementTree.parse(path).getroot()

                    # This should be good enough for us.
                    # If this is true they are definetly the same etree, it may
                    # miss some equivalent trees
                    if ElementTree.tostring(old) == ElementTree.tostring(root):
                        return False

                tree.write(path)
                return True

        return False

    @property
    def visible(self):
        return self._visible

    @visible.setter
    def visible(self, value: bool) -> None:
        self._visible = value

        if self.element:
            if value:
                self.element.set("style", "display:inline")
            else:
                self.element.set("style", "display:none")

    def __iter__(self):
        self.visible = True

        if not self.children:
            yield self

        for child in self.children:
            yield from child

        self.visible = False


def layer(element: ElementTree.Element) -> Tree | None:
    if element.get(inkscape("groupmode")) != "layer":
        return None

    label = element.get(inkscape("label"))

    if label is None:
        return None

    if label[0] == "(" and label[-1] == ")":
        return None

    tree = Tree(element)
    tree.visible = False

    for child in element:
        if subtree := layer(child):
            tree.children.append(subtree)

    return tree


def load_presentation(file: Path) -> Tree:
    """Load a presentation from an svg file on disk"""
    tree = ElementTree.parse(file)
    ElementTree.register_namespace("svg", "http://www.w3.org/2000/svg")
    root = tree.getroot()
    try:
        root.remove(
            root.findall(".{http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd}*")[0]
        )
    except IndexError:
        pass

    try:
        root.remove(root.findall(".{http://www.w3.org/2000/svg}metadata")[0])
    except IndexError:
        pass

    ns = {"xlink": "http://www.w3.org/1999/xlink", "svg": "http://www.w3.org/2000/svg"}

    for prefix, uri in ns.items():
        ElementTree.register_namespace(prefix, uri)

    # Record all the parents of our tree
    parent_map = {c: p for p in tree.iter() for c in p}

    for x in root.findall(".//svg:use", ns):
        # Get what we're linked to
        xlink = ns["xlink"]
        href = x.attrib[f"{{{xlink}}}href"]
        link_target = root.find(f".//*[@id='{href[1:]}']")
        assert link_target is not None

        # Find our parent
        parent = parent_map[x]
        index = parent[0:].index(x)

        parent.remove(x)

        # Undo the link by copying it, and transforming it where it needs to go
        new_node = copy.deepcopy(link_target)

        try:
            new_node.attrib["transform"] = x.attrib["transform"]
        except KeyError:
            translate = "translate({},{})".format(x.attrib["x"], x.attrib["y"])
            new_node.attrib["transform"] = translate

        parent.insert(index, new_node)

    slides = Tree()
    slides.tree = tree
    for child in root:
        if sub_slides := layer(child):
            slides.children.append(sub_slides)

    return slides


def find_svgs(names: list[str]) -> Iterator[Path]:
    stack = list(map(Path, names))

    while stack:
        path = stack.pop()

        if path.is_file() and path.suffix == ".svg":
            yield path
            continue

        if path.is_dir():
            stack.extend(sorted(list(path.iterdir()), reverse=True))
            continue


if __name__ == "__main__":
    main()
